name: Update Glizzy Feed

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run Glizzy Scraper
        run: python glizzy_scraper.py

      - name: Commit and push
        run: |
          git config user.name "YouGlizz Bot"
          git config user.email "bot@youglizz.com"
          git add videos.json
          git commit -m "Auto-update videos.json from Reddit" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



